language: go

arch:
  - amd64
  - arm64
  - ppc64le
jobs:
  # Sometimes it takes a very long time to spin up an ARM machine on travis.
  # Because of this, we will not require arm64 builds in order for a PR to go green.
  fast_finish: true
  allow_failures:
    - arch: arm64
    - arch: ppc64le
  include:
    - arch: amd64
    - arch: arm64
    - arch: ppc64le
    - name: Snyk
      if: branch == master AND fork == false
      node_js:
        - 12
      env:
        - NODE_OPTIONS=--max-old-space-size=8192
        - secure: fA6zOOsbgJXlHe9nkuW4XOAtfQ9QTxorDJGLA97ic1+tCWpJzJlcTJ+cW1vMQXvpmoyLzZWl8PhS9PLeHY5wgwPc+EtTAc1l9JhNPr72V0yPCuZdIwc9HHG6gDFaoy28Ms4NFwIWFST11ZaZ0BLoi11uIDScngtcvbW94/HUw9giSpAbPGAjCa1+uLw4Oci678W072b0gtaTs8HujpePB1aofBhx1p6ZVMCY/O7VjJ6UdOcyBtNL8/DfupKHAQIpbNFvqO+GpscVNY7ZNyubj7K3Fw2CGSrvZ3V0iBcliA3jhQ8+bTTE0IvuXPcy79Cid5YQgxCcmAPlwkZeo8dLMspdTFiGkFINfAZkrfODWO1wgQ9tpJtCCr/PnycBYliT1XW1lCr2Uw2K5u0cn0JHeJLUwZPBKG9vTzq8zjIQBae7ZCb7x1PcuznbQpvo0zIkDOyNTJI5w5waroZ8VBJ8VkYNe0sNw0GgeM2doHVKPkayx/I1LgqBYv2oktLf25uhIvzKR3jByCsVOiWdw9/lvluQ77F4qzyDa58M9KM3FMsP84izxEQXjrgLUwIsgqvW9B9EROW9Thllllvc1/3gVKADYbiSD03RML7W1T+q8tX7KUiru1kGGSGjX7VDy46YooiUAA/Ou8aw9mP4jjN6eTEL2moZMN1frOgI9EJ49aY=
      install:
        - npm install -g snyk
      script:
        - if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then snyk monitor --org=kiali --prune-repeated-subdependencies; fi
        - if [ "$TRAVIS_EVENT_TYPE" != "push" ]; then snyk test --org=kiali --prune-repeated-subdependencies; fi

go:
- 1.14.7

cache:
  directories:
  - $HOME/gopath/pkg/mod

  # The channel name "chat.freenode.net#kiali" is encrypted to prevent IRC spam from forks
notifications:
  irc:
    channels:
      - secure: dYuECNEpIWxWpC3J1VURDSEPM/XS29bX6bTPeaCQ+xHvek9QQ6n6e2SMHkmHYU2yXShY/AxTGKaxUrMqxsQx5VlU+tEk77zy3V9McvgxPrHLAvWsMsNkItHAD8xu6KqXDaXHhy1eYFqo0hvmycXmqOOQ/pRTGnBg4x4Gr151Ej2VgmufdKobFXFOS+VXnsitJr3GjvyLU4jIwu4oj+9svH9bI8cLyZuVFsI61ortKsAs2kjZcm8HlHCzxHCyHKlQ9JzyNXUiw6pMt19KXnzgRCkNNkCF2BbUhNSJmd97+oNb7ldvlfm7Gxx2uBiVUcOdQMO8MHJtqG1+7NDi08DrIyDPOnbN2EGPikPgHmyNjtGTKGw/M8MO97cNsBpA6jc8tWZ9dVeVHjQmy6/QzpNtKCM8u0d4Buk4+8IcAhkaP9Zdf1oKrTOYsmpjuPeGNU011NNj/O97hG9dUEqX6zfPvqgrx91KAyJeyoYaMHT9ZaRWVFUMN6kiJkmZnwAvuBOIYNH99w8LlO0SVf6ODGDIWfJybWBT/7jXfAFA9Z58yHdGmh2q8kvBXcXK+pYxmlrMKqxv52JTZCSfPBzfZfEVUd33ZocnQRINZKcgqxQQrdYJVmL07MEriuR8MxwsICz5ZkHBivHeJdSK6qUjk3f3waxletrPBW5hbnpnG0HhS+M=
    on_success: change
    on_failure: change

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/

env:
  global:
  - secure: "qy2ptBm0rm1gu2tWGRYZVB+IGy2aJXz40lrTbh/v01kE/iauK7knUYlpY4hkHBR8tTuvmDipHJJZSPhQrGLiLJU7+lSlr4X2pBJbou+hGal0pPlio379Bn3UZ0RTPE1kw8E6e007gGEcTQmFDeOCxQ1Rtm426guaL4SnXBM5D3dtQqEVhkgYGjivnOl2wrrqz1gBF/76OUfCN4nTwhJqiyiM/ELX3hYQ7CZcRQ7sZ+RqXEpR6zum+tgGauQ7zO+ebWKGn76ZaInZ4hnTx/hoiBmQ5jm6vOpOK2+Vqrskleh8QUvSRk1p1qjjUDj0gqgX2NoxqTrqSb6kMjez3hJCCz8teibuDBNqmER/mSoTFZQhMZYKwnUSe+xM9O+O2gOgNTwdm0Ejj1cY28BH02YiondG0mrX+xplFyzsDXOPdUdQdkT2YNfy29LI7fd2knWT294TPmbrYeoRqb4sQ76d+8RSJlgFpjkR8ejJT/aW3mzwO76YdJQXhuYM9JZx14whMIxWHi0Pje3/PgV7RfceyxbFs9dSaaZ5GYv8dvEsiIkTFgpEVdP45eL8VXj/6ErapjU2YYB9qzTgb+rvTPqqyP3GN3U6nd9Kd768DZvrzT6jCoua/m3lWnBiLFZXofOB9SomqaWv81VcUSIvr2uDpVl+onFBBx3C3RZM70PV5Jg="
  - secure: "gYC5NDHZBMmTIPVzxXwZBFJ99UFnrnqN9YTNz3OxrN1qSrWi3g4nNhP2lyreKhaAg5IchYvHwjgktWYE25yCvsMLfaQQXw/2wCwRnEpcMDsVzZxVfExvy8bukhKlgKr8PXU+4mMTo1E+4b+HWdCTMQf0hKt6/7ccF8udY+VxXqQ6Kg9CrRSg3MtsMJR75rOUpJ2KgNG9N5GzCNl3hxwM+F7DpHEp0YstpAWqlugTHhsKGXEUfu/DGhRWfEmQnj0u8ra3qkjsRlanLcWdCfHR4lqPVuRRkeIP3QQkgJe283xVgt6t1sIUdMOSvoSqi+T469WI+nuO9ssPBikViQSc1P2vOay1p3dIx8PKmIvRlDr+fT5d8FvTafWCDMHOrAEJ3drkbjuMo/E3OXNq3QS8aXlFc17raa+gxihSQNVV1weyifng9+IO5JRoi1B9unOwuAl71Xt34uMAjCWJ2tZS/w4c5IPUaSlaXO4ULEgn0YEjxFnrroxBexFkWlgnT8wrjOg3JUOSbNSB1X81IoSEYiDg+Ddt/zn8lS0fQwAMvsuAODdY5EnMbLFDUKOEZxMl6GVAvDzp0LxGfzFLlHTGkPBy92Ox/59qRLXVvUcCn++Dl9TvnI5g8mSTcWjmDDHyTSShzfO/y/+aMc2mQ/OEYZ7u5o8qHOgeqFjrzHN72P0="

# The project committed the vendor directory into source so there is no need for
# travis to install dep and pull down dependencies.
# Therefore, the dep-X targets are commented out here. Uncomment these if the project
# decided to no longer commit vendor dependencies into the source tree.
# See: https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory
install:
 - make swagger-install
 - make lint-install

script:
  - if [ ! -z "$(gofmt -l ${GO_FILES})" ]; then echo "These files need to be formatted:" "$(gofmt -l ${GO_FILES})";echo "Diff files:"; gofmt -d ${GO_FILES}; exit 1; fi # Gofmt Linter
  - make lint
  - make swagger-travis
  - make clean build test-race
